### ISSUE TITLE
Support for Ubuntu

### ISSUE THREAD

**Issue by rogermartensson** [itmanagerro/puppet-rkhunter#1]
When trying your module and before I updated your module to recognize Ubuntu I got this error message:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Function 'fail' does not return a value at /etc/puppet/environments/production/modules/rkhunter/manifests/params.pp:92 on node reflectortest.server.****.se
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Since Ubuntu is the same as Debian when talking about rkhunter I can't see that it shouldn't work.

**Comment by monotek** [comment]
Works for me on Unbuntu. 
Do you have stdlib module dependency installed?

**Comment by rogermartensson** [comment]
I'll close my issue since it's too old.
